#plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "https://gitlab.com/motaz-shokry/gruvbox-tmux"

#tema
set -g @gruvbox-tmux_theme "medium"
set -g @gruvbox-tmux_terminal_icon ''
set -g @gruvbox-tmux_active_terminal_icon ''
set -g @gruvbox-tmux_time_format 24H
set -g @gruvbox-tmux_window_id_style hsquare
set -g @gruvbox-tmux_pane_id_style super
set -g @gruvbox-tmux_zoom_id_style fsquare

#não uso sem isso
set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
