log_level = "warn"
position = "Top"

[[CustomModule]]
name = "Rofi"
type = "Button"
icon = ""
command = "rofi -show drun"

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[modules]
#left = [ ["Rofi", "Workspaces", "WindowTitle"] ]
left = [ ["Rofi", "Workspaces"] ]
center = [ ["CustomNotifications","Tempo", "MediaPlayer"] ]
right = [ ["Tray", "Privacy", "Settings" ] ]

[settings]
[[settings.CustomButton]]
name = "Color Picker"
icon = ""
command = "hyprpicker | wl-copy"
listen_cmd = ""

[[settings.CustomButton]]
name = "Screen Recorder"
icon = ""
command = "~/.local/bin/screen-recorder.sh"
listen_cmd = ""

[[settings.CustomButton]]
name = "Phone"
icon = ""
command = "~/.local/bin/kde-connect.sh"
listen_cmd = ""

[appearance]
# Estilos: "Solid", "Islands" ou "Floating"
style = "Solid" 
font_name = 'FiraCode Nerd Font'
scale_factor = 1.0

# Cores principais (direto no appearance)
primary_color = "#689d6a"    # Amarelo Gruvbox
success_color = "#98971a"    # Verde Gruvbox
text_color = "#ebdbb2"       # Creme claro
workspace_colors = [ "#cc241d", "#98971a", "#458588", "#b16286" ]
special_workspace_colors = [ "#fb4934", "#fe8019" ]

[appearance.background_color]
base = "#1d2021"    # Fundo principal
weak = "#282828"    # Tons de cinza/superfície
strong = "#fb4934"  # Destaque de seleção
text = "#ebdbb2"

[appearance.danger_color]
base = "#cc241d"    # Vermelho Gruvbox
weak = "#fb4934"    # Vermelho claro

[appearance.secondary_color]
base = "#3c3836"    # Azul Gruvbox

# Seção de relógio/tempo para bater com o layout
[tempo]
tempo_format = "%a %d %b %R"
weather_indicator = "IconAndTemperature"

[workspaces]
visibility_mode = "All"
enable_workspace_filling = true
max_workspaces = 4

#[window_title]
#mode = "InitialClass"
#truncate_title_after_length = 75

[media_player]
indicator_format = "Icon"
max_title_length = 50
