hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor \"Quintom_Ink\" 24")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
    hl.exec_cmd("fcitx5 -d --replace")
    -- hl.exec_cmd("ashell")
    hl.exec_cmd("noctalia")
end)
