#################
### AUTOSTART ###
#################

exec-once = ashell
exec-once = hyprpm reload -n
exec-once = hyprpaper -c ~/.config/hypr/modules/hyprpaper.conf
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor "Quintom_Snow" 24
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/gcr/ssh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hypridle -c ~/.config/hypr/modules/hypridle.conf
