hl.env("HYPRCURSOR_THEME", "Quintom_Ink")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Quintom_Ink")
hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("GTK_THEME", "Colloid-Green-Dark-Compact-Gruvbox")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("SSH_AUTH_SOCK", "$XDG_RUNTIME_DIR/gcr/ssh")
hl.env("LANG", "pt_BR.UTF-8")
hl.env("LC_ALL", "pt_BR.UTF-8")
-- hl.env("GTK_IM_MODULE", "fcitx")
-- hl.env("QT_IM_MODULE", "fcitx")
-- hl.env("XMODIFIERS", "@im=fcitx")
