#############################
### ENVIRONMENT VARIABLES ###
#############################

env = HYPRCURSOR_THEME,Quintom_Snow
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = GTK_THEME,Colloid-Green-Dark-Compact-Gruvbox
env = GDK_BACKEND,wayland,x11
