plugin {
    hyprbars {
        enabled = true
        bar_color = rgb(1d2021)
        bar_height = 20
        hyprbars-button = rgb(fb4934), 12, , hyprctl dispatch killactive
        hyprbars-button = rgb(b8bb26), 12, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(fabd2f), 12, , hyprctl dispatch movetoworkspacesilent special:minimizadas
        inactive_button_color = rgb(32302f)
        bar_text_align = left
        col.text = rgb(ebdbb2)
    }
}

bind = SUPER, TAB, hyprexpo:expo, toggle

hyprexpo-gesture = 3, vertical, expo
plugin {
    hyprexpo {
        skip_empty = false
        columns = 2
        gap_size = 5
        bg_col = rgb(282828)
        workspace_method = center first # [center/first] [workspace] e.g. first 1 or center m+1
        gesture_distance = 200 # how far is the "max" for the gesture
    }
}
