##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = ignore-maximize-requests
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:fullscreen = false
    no_focus = true
}

windowrule {
    name = ocultar-barra-gnome
    match:class = ^org\.gnome\.(Nautilus|Papers|Epiphany|Calculator|SystemMonitor|clocks|Music|Logs|baobab|Boxes|Calendar|Snapshot|Characters|Contacts|TextEditor|DiskUtility|Loupe|Evince|seahorse\.Application|Showtime|Decibels|Notes|Weather|Todo|FileRoller|Maps|Photos|font-viewer|SimpleScan)$
    hyprbars:no_bar = true
}

windowrule {
    name = ocultar-barra-pamac
    match:class = ^(org\.manjaro\.pamac\.manager|stirling-pdf)$
    hyprbars:no_bar = true
}

windowrule {
	name = "modo-janela"
}


cursor {
    hide_on_key_press = false
}
